<!-- https://courses.wesbos.com/account/access/5e4818abd9cc836465201439/view/375831618  -->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <script>
// Async is a syntax improvement for using promises
const wait = (ms = 0) => new Promise(resolve => setTimeout(resolve, ms));

function makePizza(toppings = []) {
  return (pizzaPromise = new Promise(function(resolve, reject) {
    // Reject if someone chooses pinapple topping
    if (toppings.includes('pinapple')) {
      reject('Seriously?! Get out 🍍');
    }
    // Change bake time according to number of toppings
    const amountOfTimeToBake = 500 + toppings.length * 200;
    setTimeout(() => {
      resolve(`Here is your pizza 🍕 with the toppings ${toppings.join(' ')}`);
    }, amountOfTimeToBake);
    // When it's ready you can resolve this promise
    // If something goes wrong you can reject this promise
  }));
}

// Error handling with try and catch
// Works with other stuff too
// async function go() {
//   const pizza = await makePizza(['pinapple']);
//   console.log(pizza);

//   console.log('Uh oh');
//   console.log(err);
// }

// 'Mix and match' with promise syntax

function handleError(err) {
  console.log('Ruh roh');
  console.log(err);
}

// Async functions always return a promise. So you can do promise stuff on the result
async function go() {
  // can handle error here, or..
  const pizza = await makePizza(['pinapple']); // .catch(handleError);
  console.log(pizza);
  return pizza;
}

// .. can handle error here
// go().catch(handleError);
// Can use promise methods on result of async functions
// go()
//   .then(result => {
//     console.log(result);
//   })
//   .catch(handleError);
// ***  Wes' preferred method  ***
// go().catch(handleError);

// Using higher order functions

function makeSafe(fn, errorHandler) {
  return function() {
    fn().catch(errorHandler);
  };
}

go(); // Unsafe... wont catch error

const safeGo = makeSafe(go, handleError);

safeGo();
  </script>
</body>

</html>
